# 端口号
server:
  port: 8999

hr:
  api:
    #url: http://10.40.128.28:8083
    url: http://localhost:99

#数据库连接信息
spring:
  #环境配置
    profiles:
        active: dev
        #active: prod
    # Redis数据库索引（默认为0）
    redis:
        database: 1
        # Redis服务器地址
        host: 127.0.0.1
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password:
        jedis:
            pool:
              # 连接池最大连接数（使用负值表示没有限制）
              max-active: 100
              # 连接池最大阻塞等待时间（使用负值表示没有限制）
              max-wait: 5000
              # 连接池中的最大空闲连接
              max-idle: 20
              # 连接池中的最小空闲连接
              min-idle: 0

logging:
  level:
    com.ait.mobile: trace

doosan:
  api:
    Appkey: 903750F1B8000F83E053AB80280AA264