/* Generated by Together */

package com.ait.evs;

public class ItemDetail {
	public String getPeriodID() {
		return periodID;
	}

	public void setPeriodID(String periodID) {
		this.periodID = periodID;
	}

	public String getEvEmpID() {
		return evEmpID;
	}

	public void setEvEmpID(String evEmpID) {
		this.evEmpID = evEmpID;
	}

	public String getEvEmpName() {
		return evEmpName;
	}

	public void setEvEmpName(String evEmpName) {
		this.evEmpName = evEmpName;
	}

	public String getEvProcessID() {
		return evProcessID;
	}

	public void setEvProcessID(String evProcessID) {
		this.evProcessID = evProcessID;
	}

	public String getEvProcessName() {
		return evProcessName;
	}

	public void setEvProcessName(String evProcessName) {
		this.evProcessName = evProcessName;
	}

	public String getEvItemID() {
		return evItemID;
	}

	public void setEvItemID(String evItemID) {
		this.evItemID = evItemID;
	}

	public String getEvItemName() {
		return evItemName;
	}

	public void setEvItemName(String evItemName) {
		this.evItemName = evItemName;
	}

	public String getEvItemDetail() {
		return evItemDetail;
	}

	public void setEvItemDetail(String evItemDetail) {
		this.evItemDetail = evItemDetail;
	}

	private String periodID;

	private String evEmpID;

	private String evEmpName;

	private String evProcessID;

	private String evProcessName;

	private String evItemID;

	private String evItemName;

	private String evItemDetail;
}