/* Generated by Together */

package com.ait.evs;

import java.io.Serializable;

public class EvsType implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public EvsType() {
    }

    public EvsType(String evTypeId, String evTypeName) {
        this.evTypeID = evTypeId;
        this.evTypeName = evTypeName;
    }

    public String getEvPeriodID() {
        return evPeriodID;
    }

    public void setEvPeriodID(String evPeriodID) {
        this.evPeriodID = evPeriodID;
    }

    public String getEvTypeID() {
        return evTypeID;
    }

    public void setEvTypeID(String evTypeID) {
        this.evTypeID = evTypeID;
    }

    public String getEvTypeName() {
        return evTypeName;
    }

    public void setEvTypeName(String evTypeName) {
        this.evTypeName = evTypeName;
    }

    //    public Vector getTypeByPeriod(String periodID) {
    //    }

    private String evPeriodID;

    private String evTypeID;

    private String evTypeName;

    public boolean equals(Object o) {
        if (o == null || !(o instanceof EvsType) || evTypeID == null) {
            return false;
        }

        EvsType evType = (EvsType) o;

        return evTypeID.equals(evType.evTypeID) == true ? true : false;
    }
}