server:
  port: 8999
  servlet:
    context-path: /pmapp

limit:
  minMoney: 0.01
  maxMoney: 999
  description: 最少发${limit.minMoney}元，最多发${limit.maxMoney}元

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pms?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


